<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle("图书共享系统"); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/main.css'))
                        ->prependStylesheet($this->basePath('css/lost.css'))
                        ->prependStylesheet($this->basePath('css/jcommonp.min.css'))
                        ->prependStylesheet($this->basePath('css/newfont.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/color.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/jquery-ui-1.10.3.min.js'))
            ->prependFile($this->basePath('js/jcommonp.min.js'))
            ->prependFile($this->basePath('js/scroll.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/books-logo.png') ?>" alt="图书共享商标"/>&nbsp;图书共享</a>
                </div>
                <div class="collapse navbar-collapse">
					<?php global $g;if($g["App"]->getServiceManager()->get("Books\Model\UserManager")->isLogged()):?>
					<?php echo $this->navigation("navigation")->menu()->setUlClass("nav navbar-nav")->setPartial("books/partials/menu.phtml")->render(); ?>
					<?php else:?>
					<?php echo $this->navigation("tourist-navigation")->menu()->setUlClass("nav navbar-nav")->setPartial("books/partials/menu.phtml")->render(); ?>
					<?php endif;?>

				</div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by WangMeng.</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
