<?php
 	$form->setAttribute('action', $this->url('book/default',array('controller'=>'book','action'=>'add')));
	$form->setAttribute("class","form-horizontal");
	$form->setAttribute("role","form");
	$id_b=$form->get("id_book");
	$id_u=$form->get("id_user");
	$n=$form->get("name");
	$t=$form->get("type");
	$ti=$form->get("thumb_image");
	$bi=$form->get("big_image");
	$d=$form->get("description");
	$p=$form->get("pledge");
	$s=$form->get("submit");
	
	$n->setAttribute("class","form-control");
	$t->setAttribute("class","form-control");
	$ti->setAttribute("class","form-control");
	$bi->setAttribute("class","form-control");
	$n->setAttribute("class","form-control");
	$d->setAttribute("class","form-control");
	$p->setAttribute("class","form-control");
	$s->setAttribute("class","btn btn-default");
	$form->prepare();	
	
/* 	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('id_book'));
	echo $this->formRow($form->get('id_user'));
	echo $this->formRow($form->get('name'));
	echo $this->formRow($form->get('type'));
	echo $this->formRow($form->get('thumb_image'));
	echo $this->formRow($form->get('big_image'));	
	echo $this->formRow($form->get('description'));
	echo $this->formRow($form->get('pledge'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();  */
?>
<style>
	#main-container {
		position: relative;
		height: 100%;
	}

	.header-bar {
		position: fixed;
		top:0px;
		left:0px;
		z-index: 100;
		width: 100%;
		height: 98px;
		background-color:#30608d;
		background-position:center;
		background: url('../../static/images/header.png') no-repeat;
	}

	.center-bar {
		height: 98px;
		padding-top: 15px;
		margin: 5px auto;
		padding-left:30px;
		padding-right:50px;
	}

	.row {
		padding-bottom: 5px;
	}

	.image-center {
		width: 70px;
		height: 70px;
		margin: 0px auto;
	}

	#sidebar {
		position:fixed;
		left: 0px;
		top: 50px;
		width: 230px                   ;
		height: 100%;
		background: #30608d;
		/*background: #00468E;*/
		/*background: #415a61;*/
	}
	#mCSB_1_container{
		width:100%;
		margin-right: 0px;
	}
	.sidebar-mini-hide {
		padding-left: 15px;
		letter-spacing: 2px;
	}
	div.sidebar-content{
		padding-bottom:150px;
	}
	.nav-main ul {
		padding: 0 0 0 80px;
	}

	.panel-info > .panel-heading {
		background: #30608d;
		color: #FFFFFF;
		height: 40px;
		line-height: 30px;
		text-align: left;
	}

	.btn-default {
		background: #30608d;
		color: #FFFFFF;
	}

	.newbtn {
		width: 230px;
		background-color: #2c343f;
	}

	.newbtnchild {
		width: 33.6%;
		border: none;
		border-radius: 0px;
	}

	.main {
		position: absolute;
		top: 70px;
		left: 0px;
		padding: 0px 23px;
		width: 100%;
		margin: 0 auto;
	}
</style>
<div class="main" style="display:block;">
	<div class="panel panel-info">
		<div class="panel-heading">添加图书</div>
		<div class="panel-body" style="">
			<?php echo $this->form()->openTag($form);
				echo $this->formRow($form->get('id_book'));
				echo $this->formRow($form->get('id_user'));			
			?>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $n->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($n);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $t->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formSelect($t);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $ti->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($ti);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $bi->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($bi);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $d->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($d);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $p->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($p);?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-12 col-sm-2 col-md-2 col-md-offset-1 col-lg-1 control-label">
					<?php echo $this->formSubmit($form->get('submit'));?>
				</div>
				<div class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">
					<button class="btn btn-default"><a href="<?php echo $this->url("book/default",array('controller'=>'book','action'=>'list')); ?>">返回图书列表</a></button>
				</div>
			</div>
			<?php echo $this->form()->closeTag();?>
			</div>
	</div>
</div>
</div>