<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
<li>
	<?php echo $item['name']; ?>
	<a href="<?php echo $this->url("book/default",array('controller'=>'book','action'=>'delete'),array('query'=>array('id_book'=>$item["id_book"])));?>">删除</a>
	<a href="<?php echo $this->url("book/default",array('controller'=>'book','action'=>'edit'),array('query'=>array('id_book'=>$item["id_book"])));?>">编辑</a>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,'Sliding','books/partials/pagination_control.phtml', array('route'=>'book/default','controller' => 'book','action'=>'list','id_user'=>$id_user)); ?>