<style>
    #main-container {
        position: relative;
        height: 100%;
    }
    div.sidebar-content{
        padding-bottom:150px;
    }
    .header-bar {
        position: fixed;
        top:0px;
        left:0px;
        z-index: 100;
        width: 100%;
        height: 98px;
        background-color:#30608d;
        background-position:center;
        background: url('../../static/images/header.png') no-repeat;
    }

    .center-bar {
        height: 98px;
        padding-top: 15px;
        margin: 5px auto;
        padding-left:30px;
        padding-right:50px;
    }

    .row {
        padding-bottom: 5px;
    }

    .image-center {
        width: 70px;
        height: 70px;
        margin: 0px auto;
    }

    #sidebar {
        position:fixed;
        left: 0px;
        top: 50px;
        width: 230px                   ;
        height: 100%;
        background: #30608d;
        /*background: #00468E;*/
        /*background: #415a61;*/
    }
    #mCSB_1_container{
        width:100%;
        margin-right: 0px;
    }
    .sidebar-mini-hide {
        padding-left: 15px;
        letter-spacing: 2px;
    }

    .nav-main ul {
        padding: 0 0 0 80px;
    }

    .panel-info > .panel-heading {
        background: #30608d;
        color: #FFFFFF;
        height: 40px;
        line-height: 30px;
        text-align: left;
    }

    .btn-default {
        background: #30608d;
        color: #FFFFFF;
    }

    .newbtn {
        width: 230px;
        background-color: #2c343f;
    }

    .newbtnchild {
        width: 33.6%;
        border: none;
        border-radius: 0px;
    }

	.main {
		position: absolute;
		top: 70px;
		left: 0px;
		padding: 0px 23px;
		width: 100%;
		margin: 0 auto;
	}
</style>
<div class="main" style="display:block;">
	<div class="panel panel-default">
		<div class="panel-heading">
			图书（总数：<?php echo $paginator->getTotalItemCount(); ?>）
		</div>
		<div class="panel-body table-responsive">
			<table class="table table-hover">
				<thead class="navbar-inner">
				<tr>
                        <th >名称</th>
                        <th >所在分类</th>
                        <th >押金(元)</th>
						<th >当前状态</th>
						<th >借阅次数</th>
						<th >推荐(星)</th>
                        <th >操作</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($paginator as $item):?>
					<?php 
						$id_book_borrowed=null;
						$br=$item->getBorrowedRecords();
						if(count($br)>0)$id_book_borrowed=$br[0]["id_book_borrowed"];
						
						$currStatus="可以借阅";
						if($item->isBorrowed())$currStatus="已被借走";
						else if($item->isWaitingPledge())$currStatus="待付押金";
						
						$cr=$item->getCurrRecord();
					?>
					<tr>
						<td>
							<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"page"),array("query"=>array("id_book"=>$item["id_book"]))) ?>"><?php echo $item["name"];?></a>
						</td>
						<td><a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"list"),array("query"=>array("book_type"=>$item["type"]))) ?>"><?php echo $book_types[$item["type"]]["name"];?></a></td>
						<td><?php echo $item["pledge"];?></td>
						<td><?php echo $currStatus;?></td>
						<td><?php echo $item->getBorrowCount();?></td>
						<td><?php echo $item->getAverageStar();?></td>
						<td>
							<?php if($cr!=null && $cr["id_user"]=$u["id_user"]):?>
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"return"),array("query"=>array("id_book"=>$item["id_book"],"id_user"=>$u["id_user"]))) ?>" class="btn btn-default btn-sm">还书</a>
							<?php endif;?>
							<?php if($item->isWaitingPledge() && $item["whoWantBook"]=$u["id_user"]):?>
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"payPledge"),array("query"=>array("id_book"=>$item["id_book"],"id_user"=>$u["id_user"]))) ?>" class="btn btn-default btn-sm">支付押金</a>
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"cancel"),array("query"=>array("id_book"=>$item["id_book"],"id_user"=>$u["id_user"]))) ?>" class="btn btn-default btn-sm">取消借阅</a>
							<?php endif;?>
							<?php if($cr==null && !$item->isWaitingPledge()):?>
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"borrow"),array("query"=>array("id_book"=>$item["id_book"],"id_user"=>$u["id_user"]))) ?>" class="btn btn-default btn-sm">借书</a>
							<?php endif;?>
							<?php if($id_book_borrowed!=null):?>
								<a href="<?php echo $this->url("book/default",array("controller"=>"BookFeedback","action"=>"add"),array("query"=>array("id_book_borrowed"=>$id_book_borrowed))) ?>" class="btn btn-default btn-sm">添加评论</a>
							<?php endif;?>
							<?php if($u->isManager() || $item["id_user"]==$u["id_user"]):?>
							<!--
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"edit"),array("query"=>array("id_book"=>$item["id_book"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
								<a href="<?php echo $this->url("book/default",array("controller"=>"book","action"=>"delete"),array("query"=>array("id_book"=>$item["id_book"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-close"></i></a>
							-->
							<?php endif;?>
						</td>
					</tr>
				<?php endforeach;?>
				<?php echo $this->paginationControl($this->paginator,'Sliding','books/partials/pagination_control.phtml', array('route'=>'book/default','controller' => 'book','action'=>'list')); ?>
				</tbody>
			</table>
		</div>
	</div>
</div>