<style>
    body{
        font-family: 微软雅黑;
    }
    div.head{
        width:100%;
        height: 90px;
        padding-top:30px;
    }
    div.head>div.head-center{
        height:58px;
        line-height: 24px;
        font-size:20px;
    }
    div.head>div.head-center>ul{
        list-style-type: none;
    }
    div.head>div.head-center>ul>li{
        float: left;
        padding-right:40px;
    }
    div.head>div.head-center>ul>li.head-text{
        font-size:24px;
    }
    div.book-center{
        text-align: center;
        font-size: 12px;
    }
    div.book-center>div.book-text{
        width: 100%;
        margin: 0 auto;
        text-align: center;
    }
    div.book-text>p.title{
        padding-top: 24px;
        font-size: 18px;
    }
    div.book-text>p.brief{
        font-size: 14px;
        text-align: left;
    }
</style>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="img/headbar01.jpg" alt="first">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Great minds have purpose, others have wishes.</h1>
                    <p class="lead">伟大的人有目标，平庸的人只有愿望</p>
                    <a class="btn btn-large btn-primary" href="#">more</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="img/headbar02.jpg" alt="second">
            <div class="container">
                <div class="carousel-caption">
                    <h1>there are no shortcuts to any play worth going</h1>
                    <p class="lead">去任何值得去的地方都没有捷径</p>
                    <a class="btn btn-large btn-primary" href="#">more</a>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="img/headbar03.jpg" alt="third">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Great minds have purpose, others have wishes.</h1>
                    <p class="lead">伟大的人有目标，平庸的人只有愿望</p>
                    <a class="btn btn-large btn-primary" href="#">more</a>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">my is span </span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">next</span>
    </a>
    <hr>
</div>
<div class="container-fluid">
    <div class="row head">
        <div class="head-center">
            <ul>
                <li class="head-text">大四图书专场</li>
                <li>共享交流</li>
                <li>以书会友</li>
            </ul>
        </div>
    </div>
    <div class="row">
		<?php foreach($books_for_senior as $i=>$item):?>
			<div class="col-md-3">
				<div class="book-center">
					<img src="img/book01.jpg" alt="" width="270px" height="150px">
					<div class="book-text">
						<p class="title"><?php echo $item["type"];?></p>
						<?php if(count($item["books"])==0):?>
							<p class="brief"><?php echo count($item["books"])."本书";?></p>
						<?php else:?>
							<p class="brief">此目录为空</p>
						<?php endif;?>
					</div>
				</div>
			</div>
		<?php if($i==3)break;?>
		<?php endforeach;?>
<!--		
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book02.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">考公类</p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book03.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title"> 考证书</p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book01.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">其他图书</p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
-->
    </div>
    <hr>
    <div class="row head">
        <div class="head-center">
            <ul>
                <li class="head-text">图书推荐</li>
                <li>共享交流</li>
                <li>以书会友</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="article-center">
                <img src="img/book01.jpg" alt="" height="268px" width="380px">
                <div class="article-text">
                    <p class="article-text-head">一个人怎么能变得更好</p>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="row" style="margin-left:10px;width:100%;text-align: center;">
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-left:10px;width:100%;text-align: center;">
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
                <div class="col-md-3 sm-article-center">
                    <img src="img/book02.jpg" height="100px" width="160px" alt="">
                    <div class="article-text">
                        <p class="article-text-head">一个人怎么能变得更好</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row head">
        <div class="head-center">
            <ul>
                <li class="head-text">文章推荐</li>
                <li>共享交流</li>
                <li>以书会友</li>
            </ul>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book01.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book02.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book03.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book01.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row head">
        <div class="head-center">
            <ul>
                <li class="head-text">猜你喜欢</li>
                <li>共享交流</li>
                <li>以书会友</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book01.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book02.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book03.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="book-center">
                <img src="img/book01.jpg" alt="" width="270px" height="150px">
                <div class="book-text">
                    <p class="title">茶花女 <span class="pull-right">小仲马</span></p>
                    <p class="brief">一个风尘女子的爱情故事，她的爱情是凄美的，动人的</p>
                </div>
            </div>
        </div>
    </div>
</div>

