<?php
  	$form->setAttribute('action', $this->url('book/default',array('controller'=>'User','action'=>'bookTypeManage')));
	$form->setAttribute("class","form-horizontal");
	$form->setAttribute("role","form");
	$n=$form->get("name");
	$d=$form->get("description");
	$s=$form->get("submit");
	
	$n->setAttribute("class","form-control");
	$d->setAttribute("class","form-control");
	$s->setAttribute("class","btn btn-default");	
	$form->prepare();
	
/*
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('name'));
	echo $this->formRow($form->get('description'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag(); 
	var_dump($this->types); */
?>
<style>
    #main-container {
        position: relative;
        height: 100%;
    }
    div.sidebar-content{
        padding-bottom:150px;
    }
    .header-bar {
        position: fixed;
        top:0px;
        left:0px;
        z-index: 100;
        width: 100%;
        height: 98px;
        background-color:#30608d;
        background-position:center;
        background: url('../../static/images/header.png') no-repeat;
    }

    .center-bar {
        height: 98px;
        padding-top: 15px;
        margin: 5px auto;
        padding-left:30px;
        padding-right:50px;
    }

    .row {
        padding-bottom: 5px;
    }

    .image-center {
        width: 70px;
        height: 70px;
        margin: 0px auto;
    }

    #sidebar {
        position:fixed;
        left: 0px;
        top: 50px;
        width: 230px                   ;
        height: 100%;
        background: #30608d;
        /*background: #00468E;*/
        /*background: #415a61;*/
    }
    #mCSB_1_container{
        width:100%;
        margin-right: 0px;
    }
    .sidebar-mini-hide {
        padding-left: 15px;
        letter-spacing: 2px;
    }

    .nav-main ul {
        padding: 0 0 0 80px;
    }

    .panel-info > .panel-heading {
        background: #30608d;
        color: #FFFFFF;
        height: 40px;
        line-height: 30px;
        text-align: left;
    }

    .btn-default {
        background: #30608d;
        color: #FFFFFF;
    }

    .newbtn {
        width: 230px;
        background-color: #2c343f;
    }

    .newbtnchild {
        width: 33.6%;
        border: none;
        border-radius: 0px;
    }

	.main {
		position: absolute;
		top: 70px;
		left: 0px;
		padding: 0px 23px;
		width: 100%;
		margin: 0 auto;
	}
</style>
<div class="main" style="display:block;">
    <div class="panel panel-info">
        <div class="panel-heading">添加图书分类</div>
        <div class="panel-body" style="">
			<?php echo $this->form()->openTag($form);
			
			?>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $n->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($n);?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $d->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($d);?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-12 col-sm-2 col-md-2 col-md-offset-1 col-lg-1 control-label">
					<?php echo $this->formSubmit($form->get('submit'));?>
				</div>
			</div>
			<?php echo $this->form()->closeTag();?>
        </div>
    </div>
    <form action="">
        <div class="panel panel-default">
            <div class="panel-heading">
                分类管理（总数：<?php count($types); ?>）
            </div>
            <div class="panel-body table-responsive">
                <table class="table table-hover">
                    <thead class="navbar-inner">
                    <tr>
                        <th >分类ID</th>
                        <th >分类名称</th>
						<th >分类描述</th>
                        <th >创建时间</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody>
					<?php foreach($types as $type):?>
						<tr>
							<td><?php echo $type["id"] ?></td>
							<td><?php echo $type["name"] ?></td>
							<td><?php echo $type["description"] ?></td>
							<td><?php echo $type["time"] ?></td>
							<td>
								<a href="<?php echo $this->url("book/default",array("controller"=>"user","action"=>"bookTypeManage"),array("query"=>array("operation"=>"edit","id"=>$type["id"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
								<a href="<?php echo $this->url("book/default",array("controller"=>"user","action"=>"bookTypeManage"),array("query"=>array("operation"=>"delete","id"=>$type["id"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-close"></i></a>
							</td>
						</tr>
					<?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>

<div class="main" style="display:none;">
    <div class="panel panel-info">
        <div class="panel-heading">添加图书分类</div>
        <div class="panel-body" style="">

            <form action="" method="get" class="form-horizontal" role="form">
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">分类ID</label>
                    <div class="col-xs-12 col-sm-8 col-lg-9">
                        <input class="form-control" name="keyword" id="" type="text" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">分类名称</label>
                    <div class="col-xs-12 col-sm-8 col-lg-9">
                        <input class="form-control" name="keyword" id="" type="text" value="">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">分类描述</label>
                    <div class="col-xs-12 col-sm-8 col-lg-9">
                        <input class="form-control" name="keyword" id="" type="text" value="">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12 col-sm-2 col-md-2 col-md-offset-1 col-lg-1 control-label">
                        <button class="btn btn-default"><i class="fa fa-plus"></i>添加</button>
                    </div>
                    <div class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">
                        <button class="btn btn-default">返回</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

