<?php
 	$form->setAttribute('action', $this->url('book/default',array('controller'=>'BookFeedback','action'=>'add')));
	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('id'));
	echo $this->formRow($form->get('id_book_borrowed'));
	echo $this->formRow($form->get('id_user'));
	echo $this->formRow($form->get('feedback'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag(); 
?>