<?php if($status["success"]):?>
	<?php
		$form->setAttribute('action', $this->url('book/default',array('controller'=>'article','action'=>'delete')));
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formRow($form->get('id_article'));
		echo $this->formRow($form->get('id_user'));
		echo $this->formSubmit($form->get('submit'));
		echo $this->form()->closeTag();
	?>
<?php else: ?>
	<?php
		echo $status["message"];
	?>
<?php endif;?>