<?php
 	$form->setAttribute('action', $this->url('book/default',array('controller'=>'article','action'=>'edit')));
	$form->setAttribute("class","form-horizontal");
	$form->setAttribute("role","form");
	$id_a=$form->get("id_article");
	$id_u=$form->get("id_user");
	$t=$form->get("title");
	$c=$form->get("content");
	$s=$form->get("submit");
	$t->setAttribute("class","form-control");
	$c->setAttribute("class","form-control");
	$s->setAttribute("class","btn btn-default");
	$form->prepare();
/* 	$form->prepare();
	echo $this->form()->openTag($form);
	echo $this->formRow($form->get('id_article'));
	echo $this->formRow($form->get('id_user'));
	echo $this->formRow($form->get('title'));
	echo $this->formRow($form->get('content'));
	echo $this->formSubmit($form->get('submit'));
	echo $this->form()->closeTag();  */
?>

<style>
	#main-container {
		position: relative;
		height: 100%;
	}

	.header-bar {
		position: fixed;
		top:0px;
		left:0px;
		z-index: 100;
		width: 100%;
		height: 98px;
		background-color:#30608d;
		background-position:center;
		background: url('../../static/images/header.png') no-repeat;
	}

	.center-bar {
		height: 98px;
		padding-top: 15px;
		margin: 5px auto;
		padding-left:30px;
		padding-right:50px;
	}

	.row {
		padding-bottom: 5px;
	}

	.image-center {
		width: 70px;
		height: 70px;
		margin: 0px auto;
	}

	#sidebar {
		position:fixed;
		left: 0px;
		top: 50px;
		width: 230px                   ;
		height: 100%;
		background: #30608d;
		/*background: #00468E;*/
		/*background: #415a61;*/
	}
	#mCSB_1_container{
		width:100%;
		margin-right: 0px;
	}
	.sidebar-mini-hide {
		padding-left: 15px;
		letter-spacing: 2px;
	}
	div.sidebar-content{
		padding-bottom:150px;
	}
	.nav-main ul {
		padding: 0 0 0 80px;
	}

	.panel-info > .panel-heading {
		background: #30608d;
		color: #FFFFFF;
		height: 40px;
		line-height: 30px;
		text-align: left;
	}

	.btn-default {
		background: #30608d;
		color: #FFFFFF;
	}

	.newbtn {
		width: 230px;
		background-color: #2c343f;
	}

	.newbtnchild {
		width: 33.6%;
		border: none;
		border-radius: 0px;
	}

	.main {
		position: absolute;
		top: 70px;
		left: 0px;
		padding: 0px 23px;
		width: 100%;
		margin: 0 auto;
	}
</style>
<div class="main" style="display:block;">
	<div class="panel panel-info">
		<div class="panel-heading">添加文章</div>
		<div class="panel-body" style="">
			<?php echo $this->form()->openTag($form);
				echo $this->formRow($form->get('id_article'));
				echo $this->formRow($form->get('id_user'));			
			?>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $t->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($form->get('title'));?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label"><?php echo $c->getLabel();?></label>
				<div class="col-xs-12 col-sm-8 col-lg-9">
					<?php echo $this->formInput($form->get('content'));?>
				</div>
			</div>
			<div class="form-group">
				<div class="col-xs-12 col-sm-2 col-md-2 col-md-offset-1 col-lg-1 control-label">
					<?php echo $this->formSubmit($form->get('submit'));?>
				</div>
				<div class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">
					<button class="btn btn-default"><a href="<?php echo $this->url("book/default",array('controller'=>'article','action'=>'list')); ?>">返回文章列表</a></button>
				</div>
			</div>
<!--			
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">选择分类</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<select name="status" class='form-control'>
							<option value="0">图书类一</option>
							<option value="1">图书类二</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">图书押金</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<input class="form-control" name="keyword" id="" type="text" value="">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">数量</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<div class="input-group">
							<input type="text" class="form-control">
							<span class="input-group-addon" id="basic-addon2">本</span>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">上架时间</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<input class="form-control" name="keyword" id="" type="text" value="">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">下架时间</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<input class="form-control" name="keyword" id="" type="text" value="">
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">图片</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<div class="input-group">
							<input type="text" class="form-control">
							<span class="input-group-addon" id="basic-addon2"><a href="#">选择图片</a></span>
						</div>
						<span class='help-block' style="padding-bottom: 15px;"><span style="color: red;">*</span>图片大小100*100</span>
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">详情图片</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<div class="input-group">
							<input type="text" class="form-control">
							<span class="input-group-addon" id="basic-addon2"><a href="#">选择图片</a></span>
						</div>
						<span class='help-block' style="padding-bottom: 15px;"><span style="color: red;">*</span>图片大小600*400</span>
					</div>
				</div>
				<div class="form-group">
					<label class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">是否上架</label>
					<div class="col-xs-12 col-sm-8 col-lg-9">
						<label class='radio-inline'>
							<input type='radio' value='type1' name='type' checked/>是
						</label>
						<label class='radio-inline'>
							<input type='radio' value='type2' name='type' />否
						</label>
					</div>
				</div>
				<div class="form-group">
					<div class="col-xs-12 col-sm-2 col-md-2 col-md-offset-1 col-lg-1 control-label">
						<button class="btn btn-default"><i class="fa fa-plus"></i>添加</button>
					</div>
					<div class="col-xs-12 col-sm-2 col-md-2 col-lg-1 control-label">
						<button class="btn btn-default">返回</button>
					</div>
				</div>-->
				
			<?php echo $this->form()->closeTag();?>
			</div>
	</div>
</div>
</div>

