<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
<li>
	<?php echo $item['title']; ?>
	<a href="<?php echo $this->url("book/default",array('controller'=>'article','action'=>'delete'),array('query'=>array('id_article'=>$item["id_article"])));?>">删除</a>
	<a href="<?php echo $this->url("book/default",array('controller'=>'article','action'=>'edit'),array('query'=>array('id_article'=>$item["id_article"])));?>">编辑</a>
</li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,'Sliding','books/partials/pagination_control.phtml', array('route'=>'book/default','controller' => 'article','action'=>'list','id_user'=>$id_user)); ?>