<style>
    #main-container {
        position: relative;
        height: 100%;
    }
    div.sidebar-content{
        padding-bottom:150px;
    }
    .header-bar {
        position: fixed;
        top:0px;
        left:0px;
        z-index: 100;
        width: 100%;
        height: 98px;
        background-color:#30608d;
        background-position:center;
        background: url('../../static/images/header.png') no-repeat;
    }

    .center-bar {
        height: 98px;
        padding-top: 15px;
        margin: 5px auto;
        padding-left:30px;
        padding-right:50px;
    }

    .row {
        padding-bottom: 5px;
    }

    .image-center {
        width: 70px;
        height: 70px;
        margin: 0px auto;
    }

    #sidebar {
        position:fixed;
        left: 0px;
        top: 50px;
        width: 230px                   ;
        height: 100%;
        background: #30608d;
        /*background: #00468E;*/
        /*background: #415a61;*/
    }
    #mCSB_1_container{
        width:100%;
        margin-right: 0px;
    }
    .sidebar-mini-hide {
        padding-left: 15px;
        letter-spacing: 2px;
    }

    .nav-main ul {
        padding: 0 0 0 80px;
    }

    .panel-info > .panel-heading {
        background: #30608d;
        color: #FFFFFF;
        height: 40px;
        line-height: 30px;
        text-align: left;
    }

    .btn-default {
        background: #30608d;
        color: #FFFFFF;
    }

    .newbtn {
        width: 230px;
        background-color: #2c343f;
    }

    .newbtnchild {
        width: 33.6%;
        border: none;
        border-radius: 0px;
    }

	.main {
		position: absolute;
		top: 70px;
		left: 0px;
		padding: 0px 23px;
		width: 100%;
		margin: 0 auto;
	}
</style>
<div class="main" style="display:block;">
	<div class="panel panel-default">
		<div class="panel-heading">
			文章（总数：<?php echo $paginator->getTotalItemCount(); ?>）
		</div>
		<div class="panel-body table-responsive">
			<table class="table table-hover">
				<thead class="navbar-inner">
				<tr>
                        <th >文章题目</th>
                        <th >简介</th>
                        <th >作者</th>
                        <th >创建时间</th>
                        <th >浏览次数(次)</th>
						<th >推荐(星)</th>
                        <th >操作</th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($paginator as $item):?>
					<?php 

					?>
					<tr>
						<td>
							<a href="<?php echo $this->url("book/default",array("controller"=>"article","action"=>"page"),array("query"=>array("id_article"=>$item["id_article"]))) ?>"><?php echo $item["title"];?></a>
						</td>
						<td><?php echo substr($item["content"],0,10);?></td>
						<td><a href="<?php echo $this->url("book/default",array("controller"=>"user","action"=>"page"),array("query"=>array("id_user"=>$item["id_user"]))) ?>"><?php echo $item->getUser()["name"];?></a></td>
						<td><?php echo $item["datetime"];?></td>
						<td><?php echo $item->getBrowseCount();?></td>
						<td><?php echo $item->getAverageStar();?></td>
						<td>
							<a href="<?php echo $this->url("book/default",array("controller"=>"ArticleFeedback","action"=>"add"),array("query"=>array("id_article"=>$item["id_article"]))) ?>" class="btn btn-default btn-sm">添加评论</a>
							<?php if($u->isManager() || $item["id_user"]==$u["id_user"]):?>
								<a href="<?php echo $this->url("book/default",array("controller"=>"article","action"=>"edit"),array("query"=>array("id_article"=>$item["id_article"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-edit"></i></a>
								<a href="<?php echo $this->url("book/default",array("controller"=>"article","action"=>"delete"),array("query"=>array("id_article"=>$item["id_article"]))) ?>" class="btn btn-default btn-sm"><i class="fa fa-close"></i></a>
							<?php endif;?>
						</td>
					</tr>
				<?php endforeach;?>
				<?php echo $this->paginationControl($this->paginator,'Sliding','books/partials/pagination_control.phtml', array('route'=>'book/default','controller' => 'article','action'=>'list')); ?>
				</tbody>
			</table>
		</div>
	</div>
</div>