 <!--
 See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
项 <?php echo ' 共'.$this->totalItemCount.'项'; ?>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url($this->route, array('controller'=>$this->controller,'action'=>$this->action),array('query'=>array('id_user'=>$this->id_user,'page' => $this->first))); ?>">
首页
</a> |
<?php else: ?>
<span class="disabled">首页</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url($this->route, array('controller'=>$this->controller,'action'=>$this->action),array('query'=>array('id_user'=>$this->id_user,'page' => $this->previous))); ?>">
&lt; 前一页
</a> |
<?php else: ?>
<span class="disabled">&lt; 前一页</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url($this->route, array('controller'=>$this->controller,'action'=>$this->action),array('query'=>array('id_user'=>$this->id_user,'page' => $this->next))); ?>">
下一页 &gt;
</a> |
<?php else: ?>
<span class="disabled">下一页 &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url($this->route, array('controller'=>$this->controller,'action'=>$this->action),array('query'=>array('id_user'=>$this->id_user,'page' => $this->last))); ?>">
尾页
</a>
<?php else: ?>
<span class="disabled">尾页</span>
<?php endif; ?>

</div>
<?php endif; ?>